project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - Research.qmd
      - text: "CV"
        href: "McEntee_CV_2024_short.pdf"

format:
  html:
    theme: 
      - custom.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full

editor: visual